services:
  smallsites:
    image: ghcr.io/keenfamily-us/infra/stacks/smallsites:latest
    container_name: smallsites-up
    restart: unless-stopped
    x-web:
      - fqdn: www.corastreetpress.com
        name: smallsites-corastreetpress
        port: 80
        alternate_hostnames:
          - corastreetpress.com
      - fqdn: www.okapi.io
        name: smallsites-okapi
        port: 80
        alternate_hostnames:
          - okapi.io
      - fqdn: www.payola.io
        name: smallsites-payola
        port: 80
        alternate_hostnames:
          - payola.io
