services:
  ext-proxies:
    image: public.ecr.aws/eks-distro/kubernetes/pause:v1.34.1-eks-1-34-9
    restart: unless-stopped
    x-dns:
      skip_service: true
    x-web:
      - fqdn: gulfse.cx
        redirect: https://bsky.app/profile/rogueprintco.bsky.social/post/3li2dzvrnvs22
        alternate_hostnames:
          - www.gulfse.cx
          - golfse.cx
          - www.golfse.cx
      - fqdn: www.masteringmodernpayments.com
        redirect: https://www.petekeen.net
        alternate_hostnames:
          - mstr.mp
          - www.masteringmodernpayments.com
          - masteringmodernpayments.net
          - www.masteringmodernpayments.net
          - masteringmodernpayments.org
          - www.masteringmodernpayments.org
