services:
  gatus:
    container_name: gatus-up
    image: twinproduction/gatus:latest
    environment:
      - GATUS_CONFIG_PATH=/config
      - CONFIGS_SHA
      - GATUS_API_TOKEN_hermes
      - GATUS_API_TOKEN_hypnotoad_docker
      - GATUS_API_TOKEN_hypnotoad_docker_test
      - GATUS_API_TOKEN_lrrr_docker
      - GATUS_API_TOKEN_ord2
      - GATUS_API_TOKEN_rpi
      - GATUS_API_TOKEN_shed
    volumes:
      - ${CONFIGS_DIR}/gatus/config:/config
      - /data/gatus:/data/
    x-op-items:
      - g6tkyx7ryhhdig3vgspawa6c2m
    x-web:
      hostname: gatus
      port: 8080
      dashboard:
        name: Gatus
        subtitle: Service monitoring
        category: Network Services
        logo: icons/svg/gatus.svg
