services:
  homer:
    container_name: homer-up
    hostname: homer
    image: ghcr.io/keenfamily-us/infra/stacks/homer:latest
    restart: unless-stopped
    environment:
      - INIT_ASSETS=0
      - CONFIGS_SHA
    volumes:
      - ${CONFIGS_DIR}/homer/assets:/www/assets
    x-web:
      port: 8080
      fqdn: keen.land
