x-common-zigbee: &common-zigbee
  image: ghcr.io/koenkk/zigbee2mqtt:2
  restart: always
  stop_signal: SIGINT
  environment:
    - TZ
  x-web:
    port: 8080

services:
  zigbee-house:
    <<: *common-zigbee
    container_name: zigbee-house
    hostname: zigbee-house
    volumes:
      - /data/zigbee/house:/app/data
    x-backup:
      paths:
        - /data/zigbee/house

  zigbee-office:
    <<: *common-zigbee
    container_name: zigbee-office
    hostname: zigbee-office
    volumes:
      - /data/zigbee/office:/app/data
    x-backup:
      paths:
        - /data/zigbee/office      
