services:
  local-proxies:
    image: public.ecr.aws/eks-distro/kubernetes/pause:v1.34.1-eks-1-34-9
    restart: unless-stopped
    x-dns:
      skip_service: true
    x-web:
      - fqdn: unifi.keen.land
        upstream: https://10.73.95.7:8443
      - fqdn: sabnzbd.keen.land
        upstream: http://10.73.95.84:30055
